export const products = [
  {
    name: "gaming pc AMD Ryzen 5",
    category: "desktop",
    subCategory: "Gaming",
    description: "amd gaming pc",
    stock: 1,
    warranty: "3 years",
    manufacturer: "AMD",
    productModel: "Z999",
    imageUrl: "",
    color: "white",
    dimensions: {
      height: "50cm",
      width: "40cm",
      length: "70cm",
      weight: "7kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "AMD Ryzen 5 5500" },
      { specName: "Video Card", specDesc: "Geforce RTX 3070" },
      { specName: "MotherBoard", specDesc: "Gigabyte A520M" },
      { specName: "Memory", specDesc: "Corsair 16GB DDR5" },
      { specName: "Storage", specDesc: "Samsung 1TB" },
      { specName: "Power Supply", specDesc: "Antec Gold 850W" },
      { specName: "Case", specDesc: "Antec AX20" },
      { specName: "System", specDesc: "Windows 11" },
    ],
    price: 5000,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "gaming pc Intel Core i5",
    category: "desktop",
    subCategory: "Gaming",
    description: "intel gaming pc",
    stock: 1,
    warranty: "3 years",
    manufacturer: "Intel",
    productModel: "A123",
    imageUrl: "",
    color: "black",
    dimensions: {
      height: "50cm",
      width: "40cm",
      length: "70cm",
      weight: "7kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel Core i5 12400" },
      { specName: "Video Card", specDesc: "Geforce GTX 1660 SUPER" },
      { specName: "MotherBoard", specDesc: "MSI PRO B760M" },
      { specName: "Memory", specDesc: "Kingston 32GB DDR4" },
      { specName: "Storage", specDesc: "Kingston 1TB" },
      { specName: "Power Supply", specDesc: "FSP HYPER 600W" },
      { specName: "Case", specDesc: "CoolerMaster B330" },
      { specName: "System", specDesc: "None" },
    ],
    price: 3000,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "gaming pc AMD Ryzen 7",
    category: "desktop",
    subCategory: "Gaming",
    description: "amd gaming pc",
    stock: 1,
    warranty: "3 years",
    manufacturer: "AMD",
    productModel: "E435T",
    imageUrl: "",
    color: "blue",
    dimensions: {
      height: "50cm",
      width: "40cm",
      length: "70cm",
      weight: "7kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "AMD Ryzen 7 7700" },
      { specName: "Video Card", specDesc: "Geforce RTX 3080" },
      { specName: "MotherBoard", specDesc: "Gigabyte A520M" },
      { specName: "Memory", specDesc: "Corsair 32GB DDR5" },
      { specName: "Storage", specDesc: "Samsung 2TB" },
      { specName: "Power Supply", specDesc: "Antec Gold 850W" },
      { specName: "Case", specDesc: "Antec AX20" },
      { specName: "System", specDesc: "Windows 11" },
    ],
    price: 9000,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "gaming pc Intel Core i9",
    category: "desktop",
    subCategory: "Gaming",
    description: "intel gaming pc",
    stock: 1,
    warranty: "3 years",
    manufacturer: "Intel",
    productModel: "I9N45",
    imageUrl: "",
    color: "red",
    dimensions: {
      height: "50cm",
      width: "40cm",
      length: "70cm",
      weight: "7kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel Core i9 13200" },
      { specName: "Video Card", specDesc: "Geforce RTX 4070" },
      { specName: "MotherBoard", specDesc: "MSI PRO B760M" },
      { specName: "Memory", specDesc: "Kingston 32GB DDR4" },
      { specName: "Storage", specDesc: "Kingston 2TB" },
      { specName: "Power Supply", specDesc: "FSP HYPER 600W" },
      { specName: "Case", specDesc: "CoolerMaster B330" },
      { specName: "System", specDesc: "None" },
    ],
    price: 8000,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "office pc Intel Pentium Gold",
    category: "desktop",
    subCategory: "Home&Office",
    description: "Intel office pc",
    stock: 1,
    warranty: "3 years",
    manufacturer: "Intel",
    productModel: "R345",
    imageUrl: "",
    color: "white",
    dimensions: {
      height: "50cm",
      width: "40cm",
      length: "70cm",
      weight: "7kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel Pentium Gold" },
      { specName: "Video Card", specDesc: "Intel UHD Graphics 610" },
      { specName: "MotherBoard", specDesc: "Gigabyte H410M" },
      { specName: "Memory", specDesc: "Kingston 8GB DDR4" },
      { specName: "Storage", specDesc: "Kingston 250GB SATA 3" },
      { specName: "Power Supply", specDesc: "Antec 500W" },
      { specName: "Case", specDesc: "Antec P7 NEO" },
      { specName: "System", specDesc: "Windows 10" },
    ],
    price: 3000,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "office desktop Intel i5",
    category: "desktop",
    subCategory: "Home&Office",
    description: "Intel office pc",
    stock: 1,
    warranty: "3 years",
    manufacturer: "Intel",
    productModel: "R390",
    imageUrl: "",
    color: "black",
    dimensions: {
      height: "50cm",
      width: "40cm",
      length: "70cm",
      weight: "7kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel i5 13400" },
      { specName: "Video Card", specDesc: "Intel UHD Graphics 730" },
      { specName: "MotherBoard", specDesc: "Gigabyte B760M" },
      { specName: "Memory", specDesc: "Kingston 8GB DDR4" },
      { specName: "Storage", specDesc: "Kingston 500GB PCIe" },
      { specName: "Power Supply", specDesc: "Antec 500W" },
      { specName: "Case", specDesc: "Antec NX200M" },
      { specName: "System", specDesc: "Windows 11" },
    ],
    price: 3500,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "office pc Intel Pentium Gold",
    category: "desktop",
    subCategory: "Home&Office",
    description: "Intel office pc",
    stock: 1,
    warranty: "3 years",
    manufacturer: "Intel",
    productModel: "R345",
    imageUrl: "",
    color: "white",
    dimensions: {
      height: "50cm",
      width: "40cm",
      length: "70cm",
      weight: "7kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel Pentium Gold" },
      { specName: "Video Card", specDesc: "Intel UHD Graphics 610" },
      { specName: "MotherBoard", specDesc: "Gigabyte H410M" },
      { specName: "Memory", specDesc: "Kingston 8GB DDR4" },
      { specName: "Storage", specDesc: "Kingston 250GB SATA 3" },
      { specName: "Power Supply", specDesc: "Antec 500W" },
      { specName: "Case", specDesc: "Antec P7 NEO" },
      { specName: "System", specDesc: "Windows 10" },
    ],
    price: 2500,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "office desktop Intel i3",
    category: "desktop",
    subCategory: "Home&Office",
    description: "Intel office pc",
    stock: 1,
    warranty: "3 years",
    manufacturer: "Intel",
    productModel: "R390",
    imageUrl: "",
    color: "black",
    dimensions: {
      height: "50cm",
      width: "40cm",
      length: "70cm",
      weight: "7kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel i3 11400" },
      { specName: "Video Card", specDesc: "Intel UHD Graphics 730" },
      { specName: "MotherBoard", specDesc: "Gigabyte B760M" },
      { specName: "Memory", specDesc: "Kingston 8GB DDR4" },
      { specName: "Storage", specDesc: "Kingston 500GB PCIe" },
      { specName: "Power Supply", specDesc: "Antec 500W" },
      { specName: "Case", specDesc: "Antec NX200M" },
      { specName: "System", specDesc: "Windows 11" },
    ],
    price: 2300,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Asus TUF gaming f15 laptop",
    category: "laptop",
    subCategory: "Gaming",
    description: "intel gaming laptop",
    stock: 5,
    warranty: "3 years",
    manufacturer: "Asus",
    productModel: "FX507ZU4-LP057W",
    imageUrl: "",
    color: "black",
    dimensions: {
      height: "40cm",
      width: "35cm",
      length: "25cm",
      weight: "4kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel Core i7 12700" },
      { specName: "Video Card", specDesc: "Geforce RTX 4050" },
      { specName: "Battery", specDesc: "90WHrs, 4S1P, 4-cell Li-ion" },
      { specName: "Memory", specDesc: "16GB DDR4" },
      { specName: "Storage", specDesc: "1TB PCIE 4.0 NVMe M.2" },
      { specName: "Resolution", specDesc: "FHD 1920x1080 16:9" },
      { specName: "Refresh Rate", specDesc: "144HZ" },
      { specName: "System", specDesc: "Windows 10" },
    ],
    price: 7000,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Lenovo Legion Slim",
    category: "laptop",
    subCategory: "Gaming",
    description: "AMD gaming laptop",
    stock: 7,
    warranty: "3 years",
    manufacturer: "Lenovo",
    productModel: "82Y5003SIV",
    imageUrl: "",
    color: "white",
    dimensions: {
      height: "40cm",
      width: "35cm",
      length: "25cm",
      weight: "4kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "AMD Ryzen 7 7840" },
      { specName: "Video Card", specDesc: "Geforce RTX 3050" },
      { specName: "Battery", specDesc: "Integrated Li-Polymer 80Wh battery" },
      { specName: "Memory", specDesc: "16GB DDR5" },
      { specName: "Storage", specDesc: "1TB PCIE 4.0 NVMe M.2" },
      { specName: "Resolution", specDesc: "WQXGA 2880x1800 16:10" },
      { specName: "Refresh Rate", specDesc: "120Hz" },
      { specName: "System", specDesc: "None" },
    ],
    price: 6500,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Asus TUF gaming a15 laptop",
    category: "laptop",
    subCategory: "Gaming",
    description: "AMD gaming laptop",
    stock: 5,
    warranty: "3 years",
    manufacturer: "Asus",
    productModel: "FA507NV-LP020",
    imageUrl: "",
    color: "grey",
    dimensions: {
      height: "40cm",
      width: "35cm",
      length: "25cm",
      weight: "4kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel Core i7 12700" },
      { specName: "Video Card", specDesc: "Geforce RTX 4050" },
      { specName: "Battery", specDesc: "90WHrs, 4S1P, 4-cell Li-ion" },
      { specName: "Memory", specDesc: "16GB DDR4" },
      { specName: "Storage", specDesc: "1TB PCIE 4.0 NVMe M.2" },
      { specName: "Resolution", specDesc: "FHD 1920x1080 16:9" },
      { specName: "Refresh Rate", specDesc: "144HZ" },
      { specName: "System", specDesc: "Windows 10" },
    ],
    price: 7500,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Lenovo Lenovo Legion 5-16IRX9",
    category: "laptop",
    subCategory: "Gaming",
    description: "AMD gaming laptop",
    stock: 7,
    warranty: "3 years",
    manufacturer: "Lenovo",
    productModel: "83DG0089IV",
    imageUrl: "",
    color: "grey",
    dimensions: {
      height: "40cm",
      width: "35cm",
      length: "25cm",
      weight: "4kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "AMD Ryzen 7 7840" },
      { specName: "Video Card", specDesc: "Geforce RTX 3050" },
      { specName: "Battery", specDesc: "Integrated Li-Polymer 80Wh battery" },
      { specName: "Memory", specDesc: "16GB DDR5" },
      { specName: "Storage", specDesc: "1TB PCIE 4.0 NVMe M.2" },
      { specName: "Resolution", specDesc: "WQXGA 2880x1800 16:10" },
      { specName: "Refresh Rate", specDesc: "120Hz" },
      { specName: "System", specDesc: "None" },
    ],
    price: 6800,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Laptop Lenovo Ideapad 3",
    category: "laptop",
    subCategory: "Home&Office",
    description: "Lenovo Ideapad 3 laptop",
    stock: 10,
    warranty: "1 year",
    manufacturer: "Lenovo",
    productModel: "82RK035IV",
    imageUrl: "",
    color: "silver",
    dimensions: {
      height: "40cm",
      width: "35cm",
      length: "25cm",
      weight: "4kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel i3 1215U" },
      { specName: "Video Card", specDesc: "Intel UHD Graphics" },
      { specName: "Battery", specDesc: "Integrated 45Wh" },
      { specName: "Memory", specDesc: "8GB DDR4" },
      { specName: "Storage", specDesc: "256GB SSD M.2" },
      { specName: "Resolution", specDesc: "FHD 1920X1080" },
      { specName: "Refresh Rate", specDesc: "60Hz" },
      { specName: "System", specDesc: "None" },
    ],
    price: 2000,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Laptop Asus Vivobook",
    category: "laptop",
    subCategory: "Home&Office",
    description: "Asus Vivobook laptop",
    stock: 9,
    warranty: "1 year",
    manufacturer: "Asus",
    productModel: "Vivobook 15 X1504VA",
    imageUrl: "",
    color: "cool silver",
    dimensions: {
      height: "40cm",
      width: "35cm",
      length: "25cm",
      weight: "4kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel Core i3 1315U" },
      { specName: "Video Card", specDesc: "Intel UHD Graphics" },
      { specName: "Battery", specDesc: "42WHrs, 3S1P, 3-cell Li-ion" },
      { specName: "Memory", specDesc: "8GB DDR4" },
      { specName: "Storage", specDesc: "512GB M.2 NVMe PCIe® 3.0 SSD" },
      { specName: "Resolution", specDesc: "FHD 1920X1080" },
      { specName: "Refresh Rate", specDesc: "60Hz" },
      { specName: "System", specDesc: "Windows 11" },
    ],
    price: 1900,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Laptop Lenovo Ideapad 3",
    category: "laptop",
    subCategory: "Home&Office",
    description: "Lenovo Ideapad 3 laptop",
    stock: 10,
    warranty: "1 year",
    manufacturer: "Lenovo",
    productModel: "82RK035IV",
    imageUrl: "",
    color: "silver",
    dimensions: {
      height: "40cm",
      width: "35cm",
      length: "25cm",
      weight: "4kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel i3 1215U" },
      { specName: "Video Card", specDesc: "Intel UHD Graphics" },
      { specName: "Battery", specDesc: "Integrated 45Wh" },
      { specName: "Memory", specDesc: "8GB DDR4" },
      { specName: "Storage", specDesc: "256GB SSD M.2" },
      { specName: "Resolution", specDesc: "FHD 1920X1080" },
      { specName: "Refresh Rate", specDesc: "60Hz" },
      { specName: "System", specDesc: "None" },
    ],
    price: 2000,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Laptop Asus Vivobook",
    category: "laptop",
    subCategory: "Home&Office",
    description: "Asus Vivobook laptop",
    stock: 9,
    warranty: "1 year",
    manufacturer: "Asus",
    productModel: "Vivobook 15 X1504VA",
    imageUrl: "",
    color: "cool silver",
    dimensions: {
      height: "40cm",
      width: "35cm",
      length: "25cm",
      weight: "4kg",
    },
    specifications: [
      { specName: "Processor", specDesc: "Intel Core i3 1315U" },
      { specName: "Video Card", specDesc: "Intel UHD Graphics" },
      { specName: "Battery", specDesc: "42WHrs, 3S1P, 3-cell Li-ion" },
      { specName: "Memory", specDesc: "8GB DDR4" },
      { specName: "Storage", specDesc: "512GB M.2 NVMe PCIe® 3.0 SSD" },
      { specName: "Resolution", specDesc: "FHD 1920X1080" },
      { specName: "Refresh Rate", specDesc: "60Hz" },
      { specName: "System", specDesc: "Windows 11" },
    ],
    price: 1900,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "AMD Ryzen 5 8600G 4.3GHz AM5",
    category: "hardware",
    subCategory: "Processors",
    description: "AMD Ryzen Processor",
    stock: 20,
    warranty: "3 years",
    manufacturer: "AMD",
    productModel: "Ryzen 5 8600G",
    imageUrl: "",
    specifications: [],
    price: 1100,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Intel Core i5 14600 2.7 Ghz",
    category: "hardware",
    subCategory: "Processors",
    description: "Intel Core Processor",
    stock: 15,
    warranty: "3 years",
    manufacturer: "Intel",
    productModel: "i5 14600",
    imageUrl: "",
    specifications: [],
    price: 1100,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "AMD Ryzen 5 8600G 4.3GHz AM5",
    category: "hardware",
    subCategory: "Processors",
    description: "AMD Ryzen Processor",
    stock: 20,
    warranty: "3 years",
    manufacturer: "AMD",
    productModel: "Ryzen 5 8600G",
    imageUrl: "",
    specifications: [],
    price: 1100,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Intel Core i5 14600 2.7 Ghz",
    category: "hardware",
    subCategory: "Processors",
    description: "Intel Core Processor",
    stock: 15,
    warranty: "3 years",
    manufacturer: "Intel",
    productModel: "i5 14600",
    imageUrl: "",
    specifications: [],
    price: 1100,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Asus Geforce RTX 3060",
    category: "hardware",
    subCategory: "VideoCards",
    description: "Asus Geforce RTX 3060 video card",
    stock: 13,
    warranty: "3 years",
    manufacturer: "Nvidia",
    productModel: "Geforce RTX 3060",
    imageUrl: "",
    specifications: [
      { specName: "Slot", specDesc: "PCI Express 4.0" },
      { specName: "Power", specDesc: "650W" },
      { specName: "Connections", specDesc: "HDMI x2 DP x3" },
    ],
    dimensions: {
      height: "4cm",
      width: "12cm",
      length: "24cm",
    },
    price: 1600,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Asus TUF gaming Radeon RX 7800 XT OC",
    category: "hardware",
    subCategory: "VideoCards",
    description: "Asus Radeon RX 7800 XT OC video card",
    stock: 12,
    warranty: "3 years",
    manufacturer: "AMD",
    productModel: "Radeon RX 7800 XT",
    imageUrl: "",
    specifications: [
      { specName: "Slot", specDesc: "PCI Express 4.0" },
      { specName: "Power", specDesc: "750W" },
      { specName: "Connections", specDesc: "HDMI x1 DP x3" },
    ],
    dimensions: {
      height: "6cm",
      width: "15cm",
      length: "31cm",
    },
    price: 2800,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Asus Geforce RTX 3060",
    category: "hardware",
    subCategory: "VideoCards",
    description: "Asus Geforce RTX 3060 video card",
    stock: 13,
    warranty: "3 years",
    manufacturer: "Nvidia",
    productModel: "Geforce RTX 3060",
    imageUrl: "",
    specifications: [
      { specName: "Slot", specDesc: "PCI Express 4.0" },
      { specName: "Power", specDesc: "650W" },
      { specName: "Connections", specDesc: "HDMI x2 DP x3" },
    ],
    dimensions: {
      height: "4cm",
      width: "12cm",
      length: "24cm",
    },
    price: 1600,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Asus TUF gaming Radeon RX 7800 XT OC",
    category: "hardware",
    subCategory: "VideoCards",
    description: "Asus Radeon RX 7800 XT OC video card",
    stock: 12,
    warranty: "3 years",
    manufacturer: "AMD",
    productModel: "Radeon RX 7800 XT",
    imageUrl: "",
    specifications: [
      { specName: "Slot", specDesc: "PCI Express 4.0" },
      { specName: "Power", specDesc: "750W" },
      { specName: "Connections", specDesc: "HDMI x1 DP x3" },
    ],
    dimensions: {
      height: "6cm",
      width: "15cm",
      length: "31cm",
    },
    price: 2800,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Asus ROG MAXIMUS Z790",
    category: "hardware",
    subCategory: "Motherboards",
    description: "Asus ROG MAXIMUS Z790 motherboard",
    stock: 7,
    warranty: "3 years",
    manufacturer: "Asus",
    productModel: "MAXIMUS Z790",
    imageUrl: "",
    specifications: [
      { specName: "Chipset", specDesc: "Intel Z790" },
      { specName: "Memory", specDesc: "4x DIMM slots DDR5" },
      { specName: "Connections", specDesc: "2 x Thunderbolt 4 ports" },
    ],
    dimensions: {
      height: "30cm",
      width: "24cm",
    },
    price: 3200,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "MSI PRO B550M AM4",
    category: "hardware",
    subCategory: "Motherboards",
    description: "MSI PRO B550M AM4 motherboard",
    stock: 10,
    warranty: "3 years",
    manufacturer: "MSI",
    productModel: "PRO B550M AM4",
    imageUrl: "",
    specifications: [
      { specName: "Chipset", specDesc: "AMD B550" },
      { specName: "Memory", specDesc: "4x DDR4" },
      { specName: "Slots", specDesc: "1x PCIe 3.0 X16, 2x PCIe 3.0 x1" },
    ],
    dimensions: {
      height: "24cm",
      width: "24cm",
    },
    price: 530,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Asus ROG MAXIMUS Z790",
    category: "hardware",
    subCategory: "Motherboards",
    description: "Asus ROG MAXIMUS Z790 motherboard",
    stock: 7,
    warranty: "3 years",
    manufacturer: "Asus",
    productModel: "MAXIMUS Z790",
    imageUrl: "",
    specifications: [
      { specName: "Chipset", specDesc: "Intel Z790" },
      { specName: "Memory", specDesc: "4x DIMM slots DDR5" },
      { specName: "Connections", specDesc: "2 x Thunderbolt 4 ports" },
    ],
    dimensions: {
      height: "30cm",
      width: "24cm",
    },
    price: 3200,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "MSI PRO B550M AM4",
    category: "hardware",
    subCategory: "Motherboards",
    description: "MSI PRO B550M AM4 motherboard",
    stock: 10,
    warranty: "3 years",
    manufacturer: "MSI",
    productModel: "PRO B550M AM4",
    imageUrl: "",
    specifications: [
      { specName: "Chipset", specDesc: "AMD B550" },
      { specName: "Memory", specDesc: "4x DDR4" },
      { specName: "Slots", specDesc: "1x PCIe 3.0 X16, 2x PCIe 3.0 x1" },
    ],
    dimensions: {
      height: "24cm",
      width: "24cm",
    },
    price: 530,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "G.Skill Aegis F4-3200C16S-8GIS 8GB",
    category: "hardware",
    subCategory: "Memory",
    description: "G.Skill Aegis F4-3200C16S-8GIS 8GB desktop memory",
    stock: 20,
    warranty: "2 years",
    manufacturer: "G.Skill",
    productModel: "F4-3200C16S-8GIS",
    imageUrl: "",
    specifications: [
      { specName: "Volume", specDesc: "8GB" },
      { specName: "Type", specDesc: "DDR4" },
      { specName: "Frequency", specDesc: "3200MHz" },
    ],
    price: 105,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Netac Shadow II NTSWD4P32SP-08K 8GB DDR4",
    category: "hardware",
    subCategory: "Memory",
    description: "Netac Shadow II NTSWD4P32SP-08K 8GB DDR4 desktop memory",
    stock: 18,
    warranty: "2 years",
    manufacturer: "Netac",
    productModel: "NTSWD4P32SP-08K",
    imageUrl: "",
    specifications: [
      { specName: "Volume", specDesc: "8GB" },
      { specName: "Type", specDesc: "DDR4" },
      { specName: "Frequency", specDesc: "3200MHz" },
    ],
    price: 105,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "G.Skill Aegis F4-3200C16S-8GIS 8GB",
    category: "hardware",
    subCategory: "Memory",
    description: "G.Skill Aegis F4-3200C16S-8GIS 8GB desktop memory",
    stock: 20,
    warranty: "2 years",
    manufacturer: "G.Skill",
    productModel: "F4-3200C16S-8GIS",
    imageUrl: "",
    specifications: [
      { specName: "Volume", specDesc: "8GB" },
      { specName: "Type", specDesc: "DDR4" },
      { specName: "Frequency", specDesc: "3200MHz" },
    ],
    price: 105,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Netac Shadow II NTSWD4P32SP-08K 8GB DDR4",
    category: "hardware",
    subCategory: "Memory",
    description: "Netac Shadow II NTSWD4P32SP-08K 8GB DDR4 desktop memory",
    stock: 18,
    warranty: "2 years",
    manufacturer: "Netac",
    productModel: "NTSWD4P32SP-08K",
    imageUrl: "",
    specifications: [
      { specName: "Volume", specDesc: "8GB" },
      { specName: "Type", specDesc: "DDR4" },
      { specName: "Frequency", specDesc: "3200MHz" },
    ],
    price: 105,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "SSD Disk Kingston SA400S37",
    category: "hardware",
    subCategory: "Storage",
    description: "SSD Disk Kingston SA400S37 240GB SATA 3",
    stock: 18,
    warranty: "2 years",
    manufacturer: "Kingston",
    productModel: "SA400S37/240G",
    imageUrl: "",
    specifications: [
      { specName: "Volume", specDesc: "240GB" },
      { specName: "Interface", specDesc: "SATA 3" },
      { specName: "Speed", specDesc: "500Mbps, 350Mbps" },
    ],
    price: 119,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "SSD Disk Samsung 870 EVO MZ-77E500BW",
    category: "hardware",
    subCategory: "Storage",
    description: "SD Disk Samsung 870 EVO MZ-77E500BW 500GB SATA 3",
    stock: 18,
    warranty: "2 years",
    manufacturer: "Samsung",
    productModel: "MZ-77E500BW",
    imageUrl: "",
    specifications: [
      { specName: "Volume", specDesc: "500GB" },
      { specName: "Interface", specDesc: "SATA 3" },
      { specName: "Speed", specDesc: "560Mbps, 530Mbps" },
    ],
    price: 294,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "SSD Disk Kingston SA400S37",
    category: "hardware",
    subCategory: "Storage",
    description: "SSD Disk Kingston SA400S37 240GB SATA 3",
    stock: 18,
    warranty: "2 years",
    manufacturer: "Kingston",
    productModel: "SA400S37/240G",
    imageUrl: "",
    specifications: [
      { specName: "Volume", specDesc: "240GB" },
      { specName: "Interface", specDesc: "SATA 3" },
      { specName: "Speed", specDesc: "500Mbps, 350Mbps" },
    ],
    price: 119,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "SSD Disk Samsung 870 EVO MZ-77E500BW",
    category: "hardware",
    subCategory: "Storage",
    description: "SD Disk Samsung 870 EVO MZ-77E500BW 500GB SATA 3",
    stock: 18,
    warranty: "2 years",
    manufacturer: "Samsung",
    productModel: "MZ-77E500BW",
    imageUrl: "",
    specifications: [
      { specName: "Volume", specDesc: "500GB" },
      { specName: "Interface", specDesc: "SATA 3" },
      { specName: "Speed", specDesc: "560Mbps, 530Mbps" },
    ],
    price: 294,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Wired Mouse Gold Touch MS614",
    category: "periphery",
    subCategory: "Mice",
    description: "Wired Mouse Gold Touch MS614",
    stock: 14,
    warranty: "1 years",
    manufacturer: "Gold Touch",
    productModel: "MS614",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 16,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Gaming Mouse MSI CLUTCH GM11",
    category: "periphery",
    subCategory: "Mice",
    description: "Gaming Mouse MSI CLUTCH GM11",
    stock: 4,
    warranty: "1 years",
    manufacturer: "MSI",
    productModel: "CLUTCH GM11",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 106,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Wired Mouse Gold Touch MS614",
    category: "periphery",
    subCategory: "Mice",
    description: "Wired Mouse Gold Touch MS614",
    stock: 14,
    warranty: "1 years",
    manufacturer: "Gold Touch",
    productModel: "MS614",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 16,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Gaming Mouse MSI CLUTCH GM11",
    category: "periphery",
    subCategory: "Mice",
    description: "Gaming Mouse MSI CLUTCH GM11",
    stock: 4,
    warranty: "1 years",
    manufacturer: "MSI",
    productModel: "CLUTCH GM11",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 106,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Gaming Keyboard Lenovo Legion K300",
    category: "periphery",
    subCategory: "Keyboards",
    description: "Gaming Keyboard Lenovo Legion K300",
    stock: 8,
    warranty: "1 years",
    manufacturer: "Lenovo",
    productModel: "Legion K300",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 196,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Gaming Keyboard Logitech Prodigy Gaming G213",
    category: "periphery",
    subCategory: "Keyboards",
    description: "Gaming Keyboard Logitech Prodigy Gaming G213",
    stock: 9,
    warranty: "1 years",
    manufacturer: "Logitech",
    productModel: "Prodigy Gaming G213",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 255,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Gaming Keyboard Lenovo Legion K300",
    category: "periphery",
    subCategory: "Keyboards",
    description: "Gaming Keyboard Lenovo Legion K300",
    stock: 8,
    warranty: "1 years",
    manufacturer: "Lenovo",
    productModel: "Legion K300",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 196,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Gaming Keyboard Logitech Prodigy Gaming G213",
    category: "periphery",
    subCategory: "Keyboards",
    description: "Gaming Keyboard Logitech Prodigy Gaming G213",
    stock: 9,
    warranty: "1 years",
    manufacturer: "Logitech",
    productModel: "Prodigy Gaming G213",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 255,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Wired Headphones + Microphone Gold Touch HYG-800",
    category: "periphery",
    subCategory: "Headphones",
    description: "Wired Headphones + Microphone Gold Touch HYG-800",
    stock: 10,
    warranty: "1 years",
    manufacturer: "Gold Touch",
    productModel: "HYG-800",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 35,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Gaming Earphones COUGAR PHONTUM ESSENTIAL",
    category: "periphery",
    subCategory: "Headphones",
    description:
      "Gaming Earphones COUGAR PHONTUM ESSENTIAL pink HS-PHONTUM-E-PK",
    stock: 10,
    warranty: "1 years",
    manufacturer: "COUGAR PHONTUM",
    productModel: "HS-PHONTUM-E-PK",
    color: "pink",
    imageUrl: "",
    specifications: [],
    price: 214,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Wired Headphones + Microphone Gold Touch HYG-800",
    category: "periphery",
    subCategory: "Headphones",
    description: "Wired Headphones + Microphone Gold Touch HYG-800",
    stock: 10,
    warranty: "1 years",
    manufacturer: "Gold Touch",
    productModel: "HYG-800",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 35,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Gaming Earphones COUGAR PHONTUM ESSENTIAL",
    category: "periphery",
    subCategory: "Headphones",
    description:
      "Gaming Earphones COUGAR PHONTUM ESSENTIAL pink HS-PHONTUM-E-PK",
    stock: 10,
    warranty: "1 years",
    manufacturer: "COUGAR PHONTUM",
    productModel: "HS-PHONTUM-E-PK",
    color: "pink",
    imageUrl: "",
    specifications: [],
    price: 214,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Speakers Logitech S120 980-000012",
    category: "periphery",
    subCategory: "Speakers",
    description: "Logitech S120 980-000012 Speakers",
    stock: 10,
    warranty: "1 years",
    manufacturer: "Logitech",
    productModel: "S120 980-000012",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 80,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Speakers Logitech Z906 980-000468",
    category: "periphery",
    subCategory: "Speakers",
    description: "Logitech Z906 980-000468 Speakers",
    stock: 10,
    warranty: "1 years",
    manufacturer: "Logitech",
    productModel: "Z906 980-000468",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 1458,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Speakers Logitech S120 980-000012",
    category: "periphery",
    subCategory: "Speakers",
    description: "Logitech S120 980-000012 Speakers",
    stock: 10,
    warranty: "1 years",
    manufacturer: "Logitech",
    productModel: "S120 980-000012",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 80,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Speakers Logitech Z906 980-000468",
    category: "periphery",
    subCategory: "Speakers",
    description: "Logitech Z906 980-000468 Speakers",
    stock: 10,
    warranty: "1 years",
    manufacturer: "Logitech",
    productModel: "Z906 980-000468",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 1458,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Logitech Brio 100 Full HD 1080p",
    category: "periphery",
    subCategory: "Cameras",
    description: "Logitech Brio 100 Full HD 1080p webcam",
    stock: 10,
    warranty: "1 years",
    manufacturer: "Logitech",
    productModel: "Brio 100",
    color: "rose",
    imageUrl: "",
    specifications: [],
    price: 169,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Jabra PanaCast 4K",
    category: "periphery",
    subCategory: "Cameras",
    description: "Jabra PanaCast 4K webcam",
    stock: 2,
    warranty: "1 years",
    manufacturer: "Jabra",
    productModel: "PanaCast",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 3469,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Logitech Brio 100 Full HD 1080p",
    category: "periphery",
    subCategory: "Cameras",
    description: "Logitech Brio 100 Full HD 1080p webcam",
    stock: 10,
    warranty: "1 years",
    manufacturer: "Logitech",
    productModel: "Brio 100",
    color: "rose",
    imageUrl: "",
    specifications: [],
    price: 169,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
  {
    name: "Jabra PanaCast 4K",
    category: "periphery",
    subCategory: "Cameras",
    description: "Jabra PanaCast 4K webcam",
    stock: 2,
    warranty: "1 years",
    manufacturer: "Jabra",
    productModel: "PanaCast",
    color: "black",
    imageUrl: "",
    specifications: [],
    price: 3469,
    tags: [],
    added: {
      on: "",
      by: "",
    },
  },
];
